### ISSUE TITLE
about add noise implementation

### ISSUE THREAD

**Issue by umnooob** [diffusion-classifier/diffusion-classifier#17]
another question is about the add noise implementation

https://github.com/diffusion-classifier/diffusion-classifier/blob/a544da9c185ed93710e16444140be7b9d128c0d5/eval_prob_adaptive.py#L107-L108
https://github.com/diffusion-classifier/diffusion-classifier/blob/a544da9c185ed93710e16444140be7b9d128c0d5/diffusion/models.py#L26

1. I notice that is the implementation of DDIM or DDPM add_noise function, can I interpret this as being the same, i.e., replacing it with scheduler.add_noise(latent,noise,batch_ts)
2. the scheduler used here is EulerDiscreteScheduler, anything different from other scheduler like original DDPM? Would it be better to use this scheduler in the classification situation.

**Comment by alexlioralexli** [comment]
1. Yeah this is the same as adding the noise during DDPM/DDIM training. 
2. The actual choice of scheduler doesn't matter here. We only create the `scheduler` object to get the number of training timesteps and `alphas_cumprod`. I quickly chose `EulerDiscreteScheduler` because it happens to be the default scheduler in the `diffusers` library. Changing the scheduler to DDPM won't change the classification accuracy.

**Comment by umnooob** [comment]
Sorry for the late reply. Thanks for the detailed explanation！
